### ISSUE TITLE
프로필 수정 API

### ISSUE THREAD

**Issue by ChoiEungi** [SWM-TEAM-GOYUKKURI/ToAnyone#51]
{
  닉네임: string,
  성별: enum ["male", "female", "nonbinary", "notselected"],
  나이대 : enum ["ten", "twenty", "thirty", "fourty", "fifty", "notselected"],
  직업: enum [(추가 예정)],
  심리검사선택지: list[number]
}

**Comment by somnisomni** [comment]
직업: enum ["student", "student_univ", "management", "office_tech", "professional", "freelancer", "simple_labor", "seller", "service", "self_emp", "homemaker", "noemp_etc", "notselected"]
